// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWvxqeqgX3-oZsDaPF1iJA-Oi5nuI-Gmg',
    appId: '1:133042323045:web:5981f4140bf1468c07508c',
    messagingSenderId: '133042323045',
    projectId: 'voom-69971',
    authDomain: 'voom-69971.firebaseapp.com',
    storageBucket: 'voom-69971.appspot.com',
    measurementId: 'G-BJBC3VQ0W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2DhTiYIDyP7owFJ9affJrEjI_HRSW4Bc',
    appId: '1:133042323045:android:7c1b8dd9de1897cd07508c',
    messagingSenderId: '133042323045',
    projectId: 'voom-69971',
    storageBucket: 'voom-69971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUYgwSQVFJbeuJO3uLMM2ln4PPs2OTJ1A',
    appId: '1:133042323045:ios:297390105fdb9d1807508c',
    messagingSenderId: '133042323045',
    projectId: 'voom-69971',
    storageBucket: 'voom-69971.appspot.com',
    iosClientId: '133042323045-731m7j70un2uoqrfdib6orn8dqqtfopj.apps.googleusercontent.com',
    iosBundleId: 'com.example.voom',
  );
}
